// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHGuPQ_MxdGuisK5fKtHif_sYjv8eiMS8',
    appId: '1:374933778559:web:79ffb3c20d53e2359f0f4a',
    messagingSenderId: '374933778559',
    projectId: 'qrcode-bloc-49b5e',
    authDomain: 'qrcode-bloc-49b5e.firebaseapp.com',
    storageBucket: 'qrcode-bloc-49b5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg2wDsrmAUr6sxsF1Icu_Yz1IxY8BqbrY',
    appId: '1:374933778559:android:7dfde3cd6cb0347a9f0f4a',
    messagingSenderId: '374933778559',
    projectId: 'qrcode-bloc-49b5e',
    storageBucket: 'qrcode-bloc-49b5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxR6b6sRmDcv3W67xu22aOTqJ_TB4-4eU',
    appId: '1:374933778559:ios:caf992f21eb09b189f0f4a',
    messagingSenderId: '374933778559',
    projectId: 'qrcode-bloc-49b5e',
    storageBucket: 'qrcode-bloc-49b5e.appspot.com',
    iosBundleId: 'com.example.qrcodeBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxR6b6sRmDcv3W67xu22aOTqJ_TB4-4eU',
    appId: '1:374933778559:ios:87de64d046350ce99f0f4a',
    messagingSenderId: '374933778559',
    projectId: 'qrcode-bloc-49b5e',
    storageBucket: 'qrcode-bloc-49b5e.appspot.com',
    iosBundleId: 'com.example.qrcodeBloc.RunnerTests',
  );
}
